#!/usr/bin/env ruby
#

REGEXPS = [/PROCEDURAL\ LANGUAGE\ \-\ plpgsql\ postgres/,
 /ACL\ \-\ public\ postgres/,
 /SHELL\ TYPE\ public\ box2d\ postgres/,
 /FUNCTION\ public\ st_box2d_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ st_box2d_out\(box2d\)\ postgres/,
 /TYPE\ public\ box2d\ postgres/,
 /SHELL\ TYPE\ public\ box3d\ postgres/,
 /FUNCTION\ public\ st_box3d_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ st_box3d_out\(box3d\)\ postgres/,
 /TYPE\ public\ box3d\ postgres/,
 /SHELL\ TYPE\ public\ box3d_extent\ postgres/,
 /FUNCTION\ public\ box3d_extent_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ box3d_extent_out\(box3d_extent\)\ postgres/,
 /TYPE\ public\ box3d_extent\ postgres/,
 /SHELL\ TYPE\ public\ chip\ postgres/,
 /FUNCTION\ public\ st_chip_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ st_chip_out\(chip\)\ postgres/,
 /TYPE\ public\ chip\ postgres/,
 /SHELL\ TYPE\ public\ geometry\ postgres/,
 /FUNCTION\ public\ st_geometry_analyze\(internal\)\ postgres/,
 /FUNCTION\ public\ st_geometry_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ st_geometry_out\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_recv\(internal\)\ postgres/,
 /FUNCTION\ public\ st_geometry_send\(geometry\)\ postgres/,
 /TYPE\ public\ geometry\ postgres/,
 /TYPE\ public\ geometry_dump\ postgres/,
 /SHELL\ TYPE\ public\ pgis_abs\ postgres/,
 /FUNCTION\ public\ pgis_abs_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ pgis_abs_out\(pgis_abs\)\ postgres/,
 /TYPE\ public\ pgis_abs\ postgres/,
 /SHELL\ TYPE\ public\ spheroid\ postgres/,
 /FUNCTION\ public\ st_spheroid_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ st_spheroid_out\(spheroid\)\ postgres/,
 /TYPE\ public\ spheroid\ postgres/,
 /FUNCTION\ public\ _st_asgeojson\(integer,\ geometry,\ integer,\ integer\)\ postgres/,
 /FUNCTION\ public\ _st_asgml\(integer,\ geometry,\ integer,\ integer\)\ postgres/,
 /FUNCTION\ public\ _st_askml\(integer,\ geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ _st_contains\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ _st_containsproperly\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ _st_coveredby\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ _st_covers\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ _st_crosses\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ _st_dwithin\(geometry,\ geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ _st_intersects\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ _st_linecrossingdirection\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ _st_overlaps\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ _st_touches\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ _st_within\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ addauth\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ addauth\(text\)\ postgres/,
 /FUNCTION\ public\ addbbox\(geometry\)\ postgres/,
 /FUNCTION\ public\ addgeometrycolumn\(character\ varying,\ character\ varying,\ character\ varying,\ character\ varying,\ integer,\ character\ varying,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ addgeometrycolumn\(character\ varying,\ character\ varying,\ character\ varying,\ character\ varying,\ integer,\ character\ varying,\ integer\)\ postgres/,
 /FUNCTION\ public\ addgeometrycolumn\(character\ varying,\ character\ varying,\ character\ varying,\ integer,\ character\ varying,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ addgeometrycolumn\(character\ varying,\ character\ varying,\ character\ varying,\ integer,\ character\ varying,\ integer\)\ postgres/,
 /FUNCTION\ public\ addgeometrycolumn\(character\ varying,\ character\ varying,\ integer,\ character\ varying,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ addgeometrycolumn\(character\ varying,\ character\ varying,\ integer,\ character\ varying,\ integer\)\ postgres/,
 /FUNCTION\ public\ addpoint\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ addpoint\(geometry,\ geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ affine\(geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ affine\(geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ area\(geometry\)\ postgres/,
 /FUNCTION\ public\ area2d\(geometry\)\ postgres/,
 /FUNCTION\ public\ asbinary\(geometry\)\ postgres/,
 /FUNCTION\ public\ asbinary\(geometry,\ text\)\ postgres/,
 /FUNCTION\ public\ asewkb\(geometry\)\ postgres/,
 /FUNCTION\ public\ asewkb\(geometry,\ text\)\ postgres/,
 /FUNCTION\ public\ asewkt\(geometry\)\ postgres/,
 /FUNCTION\ public\ asgml\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ asgml\(geometry\)\ postgres/,
 /FUNCTION\ public\ ashexewkb\(geometry\)\ postgres/,
 /FUNCTION\ public\ ashexewkb\(geometry,\ text\)\ postgres/,
 /FUNCTION\ public\ askml\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ askml\(geometry\)\ postgres/,
 /FUNCTION\ public\ askml\(integer,\ geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ assvg\(geometry,\ integer,\ integer\)\ postgres/,
 /FUNCTION\ public\ assvg\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ assvg\(geometry\)\ postgres/,
 /FUNCTION\ public\ astext\(geometry\)\ postgres/,
 /FUNCTION\ public\ azimuth\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ bdmpolyfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ bdpolyfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ boundary\(geometry\)\ postgres/,
 /FUNCTION\ public\ box\(geometry\)\ postgres/,
 /FUNCTION\ public\ box\(box3d\)\ postgres/,
 /FUNCTION\ public\ box2d\(geometry\)\ postgres/,
 /FUNCTION\ public\ box2d\(box3d\)\ postgres/,
 /FUNCTION\ public\ box2d_contain\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ box2d_contained\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ box2d_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ box2d_intersects\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ box2d_left\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ box2d_out\(box2d\)\ postgres/,
 /FUNCTION\ public\ box2d_overlap\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ box2d_overleft\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ box2d_overright\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ box2d_right\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ box2d_same\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ box3d\(geometry\)\ postgres/,
 /FUNCTION\ public\ box3d\(box2d\)\ postgres/,
 /FUNCTION\ public\ box3d_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ box3d_out\(box3d\)\ postgres/,
 /FUNCTION\ public\ box3dtobox\(box3d\)\ postgres/,
 /FUNCTION\ public\ buffer\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ buffer\(geometry,\ double\ precision,\ integer\)\ postgres/,
 /FUNCTION\ public\ buildarea\(geometry\)\ postgres/,
 /FUNCTION\ public\ bytea\(geometry\)\ postgres/,
 /FUNCTION\ public\ cache_bbox\(\)\ postgres/,
 /FUNCTION\ public\ centroid\(geometry\)\ postgres/,
 /FUNCTION\ public\ checkauth\(text,\ text,\ text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ checkauth\(text,\ text,\ text\)\ postgres/,
 /FUNCTION\ public\ checkauth\(text,\ text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ checkauth\(text,\ text\)\ postgres/,
 /FUNCTION\ public\ checkauthtrigger\(\)\ postgres/,
 /FUNCTION\ public\ chip_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ chip_out\(chip\)\ postgres/,
 /FUNCTION\ public\ collect\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ collect_garray\(geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ collector\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ combine_bbox\(box2d,\ geometry\)\ postgres/,
 /FUNCTION\ public\ combine_bbox\(box3d_extent,\ geometry\)\ postgres/,
 /FUNCTION\ public\ combine_bbox\(box3d,\ geometry\)\ postgres/,
 /FUNCTION\ public\ compression\(chip\)\ postgres/,
 /FUNCTION\ public\ contains\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ convexhull\(geometry\)\ postgres/,
 /FUNCTION\ public\ crosses\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ datatype\(chip\)\ postgres/,
 /FUNCTION\ public\ difference\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ dimension\(geometry\)\ postgres/,
 /FUNCTION\ public\ disablelongtransactions\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ disablelongtransactions\(\)\ postgres/,
 /FUNCTION\ public\ disjoint\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ distance\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ distance_sphere\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ distance_spheroid\(geometry,\ geometry,\ spheroid\)\ postgres/,
 /FUNCTION\ public\ dropbbox\(geometry\)\ postgres/,
 /FUNCTION\ public\ dropgeometrycolumn\(character\ varying,\ character\ varying,\ character\ varying,\ character\ varying\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ dropgeometrycolumn\(character\ varying,\ character\ varying,\ character\ varying,\ character\ varying\)\ postgres/,
 /FUNCTION\ public\ dropgeometrycolumn\(character\ varying,\ character\ varying,\ character\ varying\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ dropgeometrycolumn\(character\ varying,\ character\ varying,\ character\ varying\)\ postgres/,
 /FUNCTION\ public\ dropgeometrycolumn\(character\ varying,\ character\ varying\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ dropgeometrycolumn\(character\ varying,\ character\ varying\)\ postgres/,
 /FUNCTION\ public\ dropgeometrytable\(character\ varying,\ character\ varying,\ character\ varying\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ dropgeometrytable\(character\ varying,\ character\ varying,\ character\ varying\)\ postgres/,
 /FUNCTION\ public\ dropgeometrytable\(character\ varying,\ character\ varying\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ dropgeometrytable\(character\ varying,\ character\ varying\)\ postgres/,
 /FUNCTION\ public\ dropgeometrytable\(character\ varying\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ dropgeometrytable\(character\ varying\)\ postgres/,
 /FUNCTION\ public\ dumprings\(geometry\)\ postgres/,
 /FUNCTION\ public\ enablelongtransactions\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ enablelongtransactions\(\)\ postgres/,
 /FUNCTION\ public\ endpoint\(geometry\)\ postgres/,
 /FUNCTION\ public\ envelope\(geometry\)\ postgres/,
 /FUNCTION\ public\ equals\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ estimated_extent\(text,\ text,\ text\)\ postgres/,
 /FUNCTION\ public\ estimated_extent\(text,\ text\)\ postgres/,
 /FUNCTION\ public\ expand\(box3d,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ expand\(box2d,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ expand\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ exteriorring\(geometry\)\ postgres/,
 /FUNCTION\ public\ factor\(chip\)\ postgres/,
 /FUNCTION\ public\ find_extent\(text,\ text,\ text\)\ postgres/,
 /FUNCTION\ public\ find_extent\(text,\ text\)\ postgres/,
 /FUNCTION\ public\ find_srid\(character\ varying,\ character\ varying,\ character\ varying\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ find_srid\(character\ varying,\ character\ varying,\ character\ varying\)\ postgres/,
 /FUNCTION\ public\ fix_geometry_columns\(\)\ postgres/,
 /FUNCTION\ public\ force_2d\(geometry\)\ postgres/,
 /FUNCTION\ public\ force_3d\(geometry\)\ postgres/,
 /FUNCTION\ public\ force_3dm\(geometry\)\ postgres/,
 /FUNCTION\ public\ force_3dz\(geometry\)\ postgres/,
 /FUNCTION\ public\ force_4d\(geometry\)\ postgres/,
 /FUNCTION\ public\ force_collection\(geometry\)\ postgres/,
 /FUNCTION\ public\ forcerhr\(geometry\)\ postgres/,
 /FUNCTION\ public\ geom_accum\(geometry\[\],\ geometry\)\ postgres/,
 /FUNCTION\ public\ geomcollfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ geomcollfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ geomcollfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ geomcollfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ geometry\(box2d\)\ postgres/,
 /FUNCTION\ public\ geometry\(box3d\)\ postgres/,
 /FUNCTION\ public\ geometry\(text\)\ postgres/,
 /FUNCTION\ public\ geometry\(chip\)\ postgres/,
 /FUNCTION\ public\ geometry\(bytea\)\ postgres/,
 /FUNCTION\ public\ geometry_above\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_analyze\(internal\)\ postgres/,
 /FUNCTION\ public\ geometry_below\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_cmp\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_contain\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_contained\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_eq\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_ge\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_gt\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ geometry_le\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_left\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_lt\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_out\(geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_overabove\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_overbelow\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_overlap\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_overleft\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_overright\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_recv\(internal\)\ postgres/,
 /FUNCTION\ public\ geometry_right\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_same\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geometry_send\(geometry\)\ postgres/,
 /FUNCTION\ public\ geometryfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ geometryfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ geometryn\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ geometrytype\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ geometrytype\(geometry\)\ postgres/,
 /FUNCTION\ public\ geomfromewkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ geomfromewkt\(text\)\ postgres/,
 /FUNCTION\ public\ geomfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ geomfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ geomfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ geomfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ geomunion\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ geosnoop\(geometry\)\ postgres/,
 /FUNCTION\ public\ get_proj4_from_srid\(integer\)\ postgres/,
 /FUNCTION\ public\ getbbox\(geometry\)\ postgres/,
 /FUNCTION\ public\ getsrid\(geometry\)\ postgres/,
 /FUNCTION\ public\ gettransactionid\(\)\ postgres/,
 /FUNCTION\ public\ hasbbox\(geometry\)\ postgres/,
 /FUNCTION\ public\ height\(chip\)\ postgres/,
 /FUNCTION\ public\ interiorringn\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ intersection\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ intersects\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ isclosed\(geometry\)\ postgres/,
 /FUNCTION\ public\ isempty\(geometry\)\ postgres/,
 /FUNCTION\ public\ isring\(geometry\)\ postgres/,
 /FUNCTION\ public\ issimple\(geometry\)\ postgres/,
 /FUNCTION\ public\ isvalid\(geometry\)\ postgres/,
 /FUNCTION\ public\ length\(geometry\)\ postgres/,
 /FUNCTION\ public\ length2d\(geometry\)\ postgres/,
 /FUNCTION\ public\ length2d_spheroid\(geometry,\ spheroid\)\ postgres/,
 /FUNCTION\ public\ length3d\(geometry\)\ postgres/,
 /FUNCTION\ public\ length3d_spheroid\(geometry,\ spheroid\)\ postgres/,
 /FUNCTION\ public\ length_spheroid\(geometry,\ spheroid\)\ postgres/,
 /FUNCTION\ public\ line_interpolate_point\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ line_locate_point\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ line_substring\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ linefrommultipoint\(geometry\)\ postgres/,
 /FUNCTION\ public\ linefromtext\(text\)\ postgres/,
 /FUNCTION\ public\ linefromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ linefromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ linefromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ linemerge\(geometry\)\ postgres/,
 /FUNCTION\ public\ linestringfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ linestringfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ linestringfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ linestringfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ locate_along_measure\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ locate_between_measures\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ lockrow\(text,\ text,\ text,\ text,\ timestamp\ without\ time\ zone\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ lockrow\(text,\ text,\ text,\ text,\ timestamp\ without\ time\ zone\)\ postgres/,
 /FUNCTION\ public\ lockrow\(text,\ text,\ text,\ text\)\ postgres/,
 /FUNCTION\ public\ lockrow\(text,\ text,\ text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ lockrow\(text,\ text,\ text\)\ postgres/,
 /FUNCTION\ public\ lockrow\(text,\ text,\ text,\ timestamp\ without\ time\ zone\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ lockrow\(text,\ text,\ text,\ timestamp\ without\ time\ zone\)\ postgres/,
 /FUNCTION\ public\ longtransactionsenabled\(\)\ postgres/,
 /FUNCTION\ public\ lwgeom_gist_compress\(internal\)\ postgres/,
 /FUNCTION\ public\ lwgeom_gist_consistent\(internal,\ geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ lwgeom_gist_decompress\(internal\)\ postgres/,
 /FUNCTION\ public\ lwgeom_gist_penalty\(internal,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ lwgeom_gist_picksplit\(internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ lwgeom_gist_same\(box2d,\ box2d,\ internal\)\ postgres/,
 /FUNCTION\ public\ lwgeom_gist_union\(bytea,\ internal\)\ postgres/,
 /FUNCTION\ public\ m\(geometry\)\ postgres/,
 /FUNCTION\ public\ makebox2d\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ makebox3d\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ makeline\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ makeline_garray\(geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ makepoint\(double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ makepoint\(double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ makepoint\(double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ makepointm\(double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ makepolygon\(geometry,\ geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ makepolygon\(geometry\)\ postgres/,
 /FUNCTION\ public\ max_distance\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ mem_size\(geometry\)\ postgres/,
 /FUNCTION\ public\ mlinefromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ mlinefromtext\(text\)\ postgres/,
 /FUNCTION\ public\ mlinefromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ mlinefromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ mpointfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ mpointfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ mpointfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ mpointfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ mpolyfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ mpolyfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ mpolyfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ mpolyfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ multi\(geometry\)\ postgres/,
 /FUNCTION\ public\ multilinefromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ multilinefromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ multilinestringfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ multilinestringfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ multipointfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ multipointfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ multipointfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ multipointfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ multipolyfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ multipolyfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ multipolygonfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ multipolygonfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ ndims\(geometry\)\ postgres/,
 /FUNCTION\ public\ noop\(geometry\)\ postgres/,
 /FUNCTION\ public\ npoints\(geometry\)\ postgres/,
 /FUNCTION\ public\ nrings\(geometry\)\ postgres/,
 /FUNCTION\ public\ numgeometries\(geometry\)\ postgres/,
 /FUNCTION\ public\ numinteriorring\(geometry\)\ postgres/,
 /FUNCTION\ public\ numinteriorrings\(geometry\)\ postgres/,
 /FUNCTION\ public\ numpoints\(geometry\)\ postgres/,
 /FUNCTION\ public\ overlaps\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ perimeter\(geometry\)\ postgres/,
 /FUNCTION\ public\ perimeter2d\(geometry\)\ postgres/,
 /FUNCTION\ public\ perimeter3d\(geometry\)\ postgres/,
 /FUNCTION\ public\ pgis_geometry_accum_finalfn\(pgis_abs\)\ postgres/,
 /FUNCTION\ public\ pgis_geometry_accum_transfn\(pgis_abs,\ geometry\)\ postgres/,
 /FUNCTION\ public\ pgis_geometry_collect_finalfn\(pgis_abs\)\ postgres/,
 /FUNCTION\ public\ pgis_geometry_makeline_finalfn\(pgis_abs\)\ postgres/,
 /FUNCTION\ public\ pgis_geometry_polygonize_finalfn\(pgis_abs\)\ postgres/,
 /FUNCTION\ public\ pgis_geometry_union_finalfn\(pgis_abs\)\ postgres/,
 /FUNCTION\ public\ point_inside_circle\(geometry,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ pointfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ pointfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ pointfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ pointfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ pointn\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ pointonsurface\(geometry\)\ postgres/,
 /FUNCTION\ public\ polyfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ polyfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ polyfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ polyfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ polygonfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ polygonfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ polygonfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ polygonfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ polygonize_garray\(geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ populate_geometry_columns\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ populate_geometry_columns\(\)\ postgres/,
 /FUNCTION\ public\ populate_geometry_columns\(oid\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ populate_geometry_columns\(tbl_oid\ oid\)\ postgres/,
 /FUNCTION\ public\ postgis_full_version\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ postgis_full_version\(\)\ postgres/,
 /FUNCTION\ public\ postgis_geos_version\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ postgis_geos_version\(\)\ postgres/,
 /FUNCTION\ public\ postgis_gist_joinsel\(internal,\ oid,\ internal,\ smallint\)\ postgres/,
 /FUNCTION\ public\ postgis_gist_sel\(internal,\ oid,\ internal,\ integer\)\ postgres/,
 /FUNCTION\ public\ postgis_lib_build_date\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ postgis_lib_build_date\(\)\ postgres/,
 /FUNCTION\ public\ postgis_lib_version\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ postgis_lib_version\(\)\ postgres/,
 /FUNCTION\ public\ postgis_proj_version\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ postgis_proj_version\(\)\ postgres/,
 /FUNCTION\ public\ postgis_scripts_build_date\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ postgis_scripts_build_date\(\)\ postgres/,
 /FUNCTION\ public\ postgis_scripts_installed\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ postgis_scripts_installed\(\)\ postgres/,
 /FUNCTION\ public\ postgis_scripts_released\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ postgis_scripts_released\(\)\ postgres/,
 /FUNCTION\ public\ postgis_uses_stats\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ postgis_uses_stats\(\)\ postgres/,
 /FUNCTION\ public\ postgis_version\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ postgis_version\(\)\ postgres/,
 /FUNCTION\ public\ probe_geometry_columns\(\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ probe_geometry_columns\(\)\ postgres/,
 /FUNCTION\ public\ relate\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ relate\(geometry,\ geometry,\ text\)\ postgres/,
 /FUNCTION\ public\ removepoint\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ rename_geometry_table_constraints\(\)\ postgres/,
 /FUNCTION\ public\ reverse\(geometry\)\ postgres/,
 /FUNCTION\ public\ rotate\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ rotatex\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ rotatey\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ rotatez\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ scale\(geometry,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ scale\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ se_envelopesintersect\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ se_is3d\(geometry\)\ postgres/,
 /FUNCTION\ public\ se_ismeasured\(geometry\)\ postgres/,
 /FUNCTION\ public\ se_locatealong\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ se_locatebetween\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ se_m\(geometry\)\ postgres/,
 /FUNCTION\ public\ se_z\(geometry\)\ postgres/,
 /FUNCTION\ public\ segmentize\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ setfactor\(chip,\ real\)\ postgres/,
 /FUNCTION\ public\ setpoint\(geometry,\ integer,\ geometry\)\ postgres/,
 /FUNCTION\ public\ setsrid\(chip,\ integer\)\ postgres/,
 /FUNCTION\ public\ setsrid\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ shift_longitude\(geometry\)\ postgres/,
 /FUNCTION\ public\ simplify\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ snaptogrid\(geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ snaptogrid\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ snaptogrid\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ snaptogrid\(geometry,\ geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ spheroid_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ spheroid_out\(spheroid\)\ postgres/,
 /FUNCTION\ public\ srid\(chip\)\ postgres/,
 /FUNCTION\ public\ srid\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_addbbox\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_addbbox\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_addpoint\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_addpoint\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_addpoint\(geometry,\ geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_addpoint\(geometry,\ geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_affine\(geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_affine\(geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_affine\(geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_affine\(geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_area\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_area\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_area2d\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_asbinary\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asbinary\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_asbinary\(geometry,\ text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asbinary\(geometry,\ text\)\ postgres/,
 /FUNCTION\ public\ st_asewkb\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asewkb\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_asewkb\(geometry,\ text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asewkb\(geometry,\ text\)\ postgres/,
 /FUNCTION\ public\ st_asewkt\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asewkt\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_asgeojson\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asgeojson\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_asgeojson\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asgeojson\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_asgeojson\(integer,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asgeojson\(integer,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_asgeojson\(integer,\ geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asgeojson\(integer,\ geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_asgeojson\(geometry,\ integer,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asgeojson\(geometry,\ integer,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_asgeojson\(integer,\ geometry,\ integer,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asgeojson\(integer,\ geometry,\ integer,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_asgml\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asgml\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_asgml\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asgml\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_asgml\(integer,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asgml\(integer,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_asgml\(integer,\ geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asgml\(integer,\ geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_asgml\(geometry,\ integer,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_asgml\(integer,\ geometry,\ integer,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_asgml\(integer,\ geometry,\ integer,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_ashexewkb\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_ashexewkb\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_ashexewkb\(geometry,\ text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_ashexewkb\(geometry,\ text\)\ postgres/,
 /FUNCTION\ public\ st_askml\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_askml\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_askml\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_askml\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_askml\(integer,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_askml\(integer,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_askml\(integer,\ geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_askml\(integer,\ geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_assvg\(geometry,\ integer,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_assvg\(geometry,\ integer,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_assvg\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_assvg\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_assvg\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_assvg\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_astext\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_astext\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_azimuth\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_azimuth\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_bdmpolyfromtext\(text,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_bdmpolyfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_bdpolyfromtext\(text,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_bdpolyfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_boundary\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_boundary\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_box\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_box\(box3d\)\ postgres/,
 /FUNCTION\ public\ st_box2d\(box3d_extent\)\ postgres/,
 /FUNCTION\ public\ st_box2d\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_box2d\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_box2d\(box3d\)\ postgres/,
 /FUNCTION\ public\ st_box2d_contain\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ st_box2d_contained\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ st_box2d_intersects\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ st_box2d_left\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ st_box2d_overlap\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ st_box2d_overleft\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ st_box2d_overright\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ st_box2d_right\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ st_box2d_same\(box2d,\ box2d\)\ postgres/,
 /FUNCTION\ public\ st_box3d\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_box3d\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_box3d\(box2d\)\ postgres/,
 /FUNCTION\ public\ st_box3d_extent\(box3d_extent\)\ postgres/,
 /FUNCTION\ public\ st_buffer\(geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_buffer\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_buffer\(geometry,\ double\ precision,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_buffer\(geometry,\ double\ precision,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_buildarea\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_buildarea\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_bytea\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_cache_bbox\(\)\ postgres/,
 /FUNCTION\ public\ st_centroid\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_centroid\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_collect\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_collect\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_collect\(geometry\[\]\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_collect\(geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ st_collect_garray\(geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ st_collector\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_combine_bbox\(box2d,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_combine_bbox\(box3d_extent,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_combine_bbox\(box3d,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_compression\(chip\)\ postgres/,
 /FUNCTION\ public\ st_contains\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_contains\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_containsproperly\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_containsproperly\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_convexhull\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_convexhull\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_coorddim\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_coorddim\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_coveredby\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_coveredby\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_covers\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_covers\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_crosses\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_crosses\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_curvetoline\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_curvetoline\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_curvetoline\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_curvetoline\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_datatype\(chip\)\ postgres/,
 /FUNCTION\ public\ st_difference\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_difference\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_dimension\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_dimension\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_disjoint\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_disjoint\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_distance\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_distance\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_distance_sphere\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_distance_sphere\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_distance_spheroid\(geometry,\ geometry,\ spheroid\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_distance_spheroid\(geometry,\ geometry,\ spheroid\)\ postgres/,
 /FUNCTION\ public\ st_dropbbox\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_dropbbox\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_dump\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_dump\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_dumprings\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_dumprings\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_dwithin\(geometry,\ geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_dwithin\(geometry,\ geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_endpoint\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_endpoint\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_envelope\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_envelope\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_equals\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_equals\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_estimated_extent\(text,\ text,\ text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_estimated_extent\(text,\ text,\ text\)\ postgres/,
 /FUNCTION\ public\ st_estimated_extent\(text,\ text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_estimated_extent\(text,\ text\)\ postgres/,
 /FUNCTION\ public\ st_expand\(box3d,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_expand\(box3d,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_expand\(box2d,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_expand\(box2d,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_expand\(geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_expand\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_exteriorring\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_exteriorring\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_factor\(chip\)\ postgres/,
 /FUNCTION\ public\ st_find_extent\(text,\ text,\ text\)\ postgres/,
 /FUNCTION\ public\ st_find_extent\(text,\ text\)\ postgres/,
 /FUNCTION\ public\ st_force_2d\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_force_2d\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_force_3d\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_force_3d\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_force_3dm\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_force_3dm\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_force_3dz\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_force_3dz\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_force_4d\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_force_4d\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_force_collection\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_force_collection\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_forcerhr\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_forcerhr\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_geohash\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geohash\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_geohash\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geohash\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_geom_accum\(geometry\[\],\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geomcollfromtext\(text,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geomcollfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_geomcollfromtext\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geomcollfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_geomcollfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_geomcollfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_geometry\(box3d_extent\)\ postgres/,
 /FUNCTION\ public\ st_geometry\(box2d\)\ postgres/,
 /FUNCTION\ public\ st_geometry\(box3d\)\ postgres/,
 /FUNCTION\ public\ st_geometry\(text\)\ postgres/,
 /FUNCTION\ public\ st_geometry\(chip\)\ postgres/,
 /FUNCTION\ public\ st_geometry\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_geometry_above\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_below\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_cmp\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_contain\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_contained\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_eq\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_ge\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_gt\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_le\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_left\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_lt\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_overabove\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_overbelow\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_overlap\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_overleft\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_overright\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_right\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometry_same\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_geometryfromtext\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geometryfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_geometryfromtext\(text,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geometryfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_geometryn\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geometryn\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_geometrytype\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geometrytype\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_geomfromewkb\(bytea\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geomfromewkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_geomfromewkt\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geomfromewkt\(text\)\ postgres/,
 /FUNCTION\ public\ st_geomfromtext\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geomfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_geomfromtext\(text,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geomfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_geomfromwkb\(bytea\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geomfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_geomfromwkb\(bytea,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_geomfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_hasarc\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_hasarc\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_hasbbox\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_hasbbox\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_height\(chip\)\ postgres/,
 /FUNCTION\ public\ st_interiorringn\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_interiorringn\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_intersection\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_intersection\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_intersects\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_intersects\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_isclosed\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_isclosed\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_isempty\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_isempty\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_isring\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_isring\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_issimple\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_issimple\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_isvalid\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_isvalid\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_isvalidreason\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_isvalidreason\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_length\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_length\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_length2d\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_length2d\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_length2d_spheroid\(geometry,\ spheroid\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_length2d_spheroid\(geometry,\ spheroid\)\ postgres/,
 /FUNCTION\ public\ st_length3d\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_length3d\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_length3d_spheroid\(geometry,\ spheroid\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_length3d_spheroid\(geometry,\ spheroid\)\ postgres/,
 /FUNCTION\ public\ st_length_spheroid\(geometry,\ spheroid\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_length_spheroid\(geometry,\ spheroid\)\ postgres/,
 /FUNCTION\ public\ st_line_interpolate_point\(geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_line_interpolate_point\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_line_locate_point\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_line_locate_point\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_line_substring\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_line_substring\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_linecrossingdirection\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_linecrossingdirection\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_linefrommultipoint\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_linefrommultipoint\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_linefromtext\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_linefromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_linefromtext\(text,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_linefromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_linefromwkb\(bytea,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_linefromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_linefromwkb\(bytea\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_linefromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_linemerge\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_linemerge\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_linestringfromwkb\(bytea,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_linestringfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_linestringfromwkb\(bytea\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_linestringfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_linetocurve\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_linetocurve\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_locate_along_measure\(geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_locate_along_measure\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_locate_between_measures\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_locate_between_measures\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_locatebetweenelevations\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_locatebetweenelevations\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_m\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_m\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_makebox2d\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_makebox2d\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_makebox3d\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_makebox3d\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_makeline\(geometry\[\]\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_makeline\(geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ st_makeline\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_makeline\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_makeline_garray\(geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ st_makepoint\(double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_makepoint\(double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_makepoint\(double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_makepoint\(double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_makepoint\(double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_makepoint\(double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_makepointm\(double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_makepointm\(double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_makepolygon\(geometry,\ geometry\[\]\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_makepolygon\(geometry,\ geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ st_makepolygon\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_makepolygon\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_max_distance\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_max_distance\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_mem_size\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_mem_size\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_minimumboundingcircle\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_minimumboundingcircle\(inputgeom\ geometry,\ segs_per_quarter\ integer\)\ postgres/,
 /FUNCTION\ public\ st_minimumboundingcircle\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_minimumboundingcircle\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_mlinefromtext\(text,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_mlinefromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_mlinefromtext\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_mlinefromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_mlinefromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_mlinefromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_mpointfromtext\(text,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_mpointfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_mpointfromtext\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_mpointfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_mpointfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_mpointfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_mpolyfromtext\(text,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_mpolyfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_mpolyfromtext\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_mpolyfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_mpolyfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_mpolyfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_multi\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_multi\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_multilinefromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_multilinestringfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_multilinestringfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_multipointfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_multipointfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_multipointfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_multipolyfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_multipolyfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_multipolygonfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_multipolygonfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_ndims\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_ndims\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_noop\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_npoints\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_npoints\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_nrings\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_nrings\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_numgeometries\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_numgeometries\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_numinteriorring\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_numinteriorring\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_numinteriorrings\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_numinteriorrings\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_numpoints\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_numpoints\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_orderingequals\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_orderingequals\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_overlaps\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_overlaps\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_perimeter\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_perimeter\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_perimeter2d\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_perimeter2d\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_perimeter3d\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_perimeter3d\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_point\(double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_point\(double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_point_inside_circle\(geometry,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_point_inside_circle\(geometry,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_pointfromtext\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_pointfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_pointfromtext\(text,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_pointfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_pointfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_pointfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_pointn\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_pointn\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_pointonsurface\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_pointonsurface\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_polyfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_polyfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_polyfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_polyfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_polygon\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_polygon\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_polygonfromtext\(text,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_polygonfromtext\(text,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_polygonfromtext\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_polygonfromtext\(text\)\ postgres/,
 /FUNCTION\ public\ st_polygonfromwkb\(bytea,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_polygonfromwkb\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_polygonize\(geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ st_polygonize_garray\(geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ st_postgis_gist_joinsel\(internal,\ oid,\ internal,\ smallint\)\ postgres/,
 /FUNCTION\ public\ st_postgis_gist_sel\(internal,\ oid,\ internal,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_relate\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_relate\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_relate\(geometry,\ geometry,\ text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_relate\(geometry,\ geometry,\ text\)\ postgres/,
 /FUNCTION\ public\ st_removepoint\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_removepoint\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_reverse\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_reverse\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_rotate\(geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_rotate\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_rotatex\(geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_rotatex\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_rotatey\(geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_rotatey\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_rotatez\(geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_rotatez\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_scale\(geometry,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_scale\(geometry,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_scale\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_scale\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_segmentize\(geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_segmentize\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_setfactor\(chip,\ real\)\ postgres/,
 /FUNCTION\ public\ st_setpoint\(geometry,\ integer,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_setpoint\(geometry,\ integer,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_setsrid\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_setsrid\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_shift_longitude\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_shift_longitude\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_simplify\(geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_simplify\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_simplifypreservetopology\(geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_simplifypreservetopology\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_snaptogrid\(geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_snaptogrid\(geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_snaptogrid\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_snaptogrid\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_snaptogrid\(geometry,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_snaptogrid\(geometry,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_snaptogrid\(geometry,\ geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_snaptogrid\(geometry,\ geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_srid\(chip\)\ postgres/,
 /FUNCTION\ public\ st_srid\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_srid\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_startpoint\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_startpoint\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_summary\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_summary\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_symdifference\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_symdifference\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_symmetricdifference\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_text\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_touches\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_touches\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_transform\(geometry,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_transform\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ st_translate\(geometry,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_translate\(geometry,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_translate\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_translate\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_transscale\(geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_transscale\(geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ st_union\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_union\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_union\(geometry\[\]\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_union\(geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ st_unite_garray\(geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ st_width\(chip\)\ postgres/,
 /FUNCTION\ public\ st_within\(geometry,\ geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_within\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ st_wkbtosql\(bytea\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_wkbtosql\(bytea\)\ postgres/,
 /FUNCTION\ public\ st_wkttosql\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_wkttosql\(text\)\ postgres/,
 /FUNCTION\ public\ st_x\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_x\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_xmax\(box3d\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_xmax\(box3d\)\ postgres/,
 /FUNCTION\ public\ st_xmin\(box3d\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_xmin\(box3d\)\ postgres/,
 /FUNCTION\ public\ st_y\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_y\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_ymax\(box3d\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_ymax\(box3d\)\ postgres/,
 /FUNCTION\ public\ st_ymin\(box3d\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_ymin\(box3d\)\ postgres/,
 /FUNCTION\ public\ st_z\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_z\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_zmax\(box3d\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_zmax\(box3d\)\ postgres/,
 /FUNCTION\ public\ st_zmflag\(geometry\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_zmflag\(geometry\)\ postgres/,
 /FUNCTION\ public\ st_zmin\(box3d\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ st_zmin\(box3d\)\ postgres/,
 /FUNCTION\ public\ startpoint\(geometry\)\ postgres/,
 /FUNCTION\ public\ summary\(geometry\)\ postgres/,
 /FUNCTION\ public\ symdifference\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ symmetricdifference\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ text\(geometry\)\ postgres/,
 /FUNCTION\ public\ touches\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ transform\(geometry,\ integer\)\ postgres/,
 /FUNCTION\ public\ transform_geometry\(geometry,\ text,\ text,\ integer\)\ postgres/,
 /FUNCTION\ public\ translate\(geometry,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ translate\(geometry,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ transscale\(geometry,\ double\ precision,\ double\ precision,\ double\ precision,\ double\ precision\)\ postgres/,
 /FUNCTION\ public\ unite_garray\(geometry\[\]\)\ postgres/,
 /FUNCTION\ public\ unlockrows\(text\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ unlockrows\(text\)\ postgres/,
 /FUNCTION\ public\ updategeometrysrid\(character\ varying,\ character\ varying,\ character\ varying,\ character\ varying,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ updategeometrysrid\(character\ varying,\ character\ varying,\ character\ varying,\ character\ varying,\ integer\)\ postgres/,
 /FUNCTION\ public\ updategeometrysrid\(character\ varying,\ character\ varying,\ character\ varying,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ updategeometrysrid\(character\ varying,\ character\ varying,\ character\ varying,\ integer\)\ postgres/,
 /FUNCTION\ public\ updategeometrysrid\(character\ varying,\ character\ varying,\ integer\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ updategeometrysrid\(character\ varying,\ character\ varying,\ integer\)\ postgres/,
 /FUNCTION\ public\ width\(chip\)\ postgres/,
 /FUNCTION\ public\ within\(geometry,\ geometry\)\ postgres/,
 /FUNCTION\ public\ x\(geometry\)\ postgres/,
 /FUNCTION\ public\ xmax\(box3d\)\ postgres/,
 /FUNCTION\ public\ xmin\(box3d\)\ postgres/,
 /FUNCTION\ public\ y\(geometry\)\ postgres/,
 /FUNCTION\ public\ ymax\(box3d\)\ postgres/,
 /FUNCTION\ public\ ymin\(box3d\)\ postgres/,
 /FUNCTION\ public\ z\(geometry\)\ postgres/,
 /FUNCTION\ public\ zmax\(box3d\)\ postgres/,
 /FUNCTION\ public\ zmflag\(geometry\)\ postgres/,
 /FUNCTION\ public\ zmin\(box3d\)\ postgres/,
 /AGGREGATE\ public\ accum\(geometry\)\ postgres/,
 /AGGREGATE\ public\ accum_old\(geometry\)\ postgres/,
 /AGGREGATE\ public\ collect\(geometry\)\ postgres/,
 /AGGREGATE\ public\ extent\(geometry\)\ postgres/,
 /AGGREGATE\ public\ extent3d\(geometry\)\ postgres/,
 /AGGREGATE\ public\ makeline\(geometry\)\ postgres/,
 /AGGREGATE\ public\ memcollect\(geometry\)\ postgres/,
 /AGGREGATE\ public\ memgeomunion\(geometry\)\ postgres/,
 /AGGREGATE\ public\ polygonize\(geometry\)\ postgres/,
 /AGGREGATE\ public\ st_accum\(geometry\)\ postgres/,
 /COMMENT\ public\ AGGREGATE\ st_accum\(geometry\)\ postgres/,
 /AGGREGATE\ public\ st_accum_old\(geometry\)\ postgres/,
 /AGGREGATE\ public\ st_collect\(geometry\)\ postgres/,
 /COMMENT\ public\ AGGREGATE\ st_collect\(geometry\)\ postgres/,
 /AGGREGATE\ public\ st_extent\(geometry\)\ postgres/,
 /COMMENT\ public\ AGGREGATE\ st_extent\(geometry\)\ postgres/,
 /AGGREGATE\ public\ st_extent3d\(geometry\)\ postgres/,
 /COMMENT\ public\ AGGREGATE\ st_extent3d\(geometry\)\ postgres/,
 /AGGREGATE\ public\ st_makeline\(geometry\)\ postgres/,
 /COMMENT\ public\ AGGREGATE\ st_makeline\(geometry\)\ postgres/,
 /AGGREGATE\ public\ st_memcollect\(geometry\)\ postgres/,
 /AGGREGATE\ public\ st_memunion\(geometry\)\ postgres/,
 /COMMENT\ public\ AGGREGATE\ st_memunion\(geometry\)\ postgres/,
 /AGGREGATE\ public\ st_polygonize\(geometry\)\ postgres/,
 /COMMENT\ public\ AGGREGATE\ st_polygonize\(geometry\)\ postgres/,
 /AGGREGATE\ public\ st_union\(geometry\)\ postgres/,
 /COMMENT\ public\ AGGREGATE\ st_union\(geometry\)\ postgres/,
 /OPERATOR\ public\ &&\ postgres/,
 /OPERATOR\ public\ &<\ postgres/,
 /OPERATOR\ public\ &<\|\ postgres/,
 /OPERATOR\ public\ &>\ postgres/,
 /OPERATOR\ public\ <\ postgres/,
 /OPERATOR\ public\ <<\ postgres/,
 /OPERATOR\ public\ <<\|\ postgres/,
 /OPERATOR\ public\ <=\ postgres/,
 /OPERATOR\ public\ =\ postgres/,
 /OPERATOR\ public\ >\ postgres/,
 /OPERATOR\ public\ >=\ postgres/,
 /OPERATOR\ public\ >>\ postgres/,
 /OPERATOR\ public\ @\ postgres/,
 /OPERATOR\ public\ \|&>\ postgres/,
 /OPERATOR\ public\ \|>>\ postgres/,
 /OPERATOR\ public\ ~\ postgres/,
 /OPERATOR\ public\ ~=\ postgres/,
 /OPERATOR\ CLASS\ public\ btree_geometry_ops\ postgres/,
 /OPERATOR\ CLASS\ public\ gist_geometry_ops\ postgres/,
 /CAST\ pg_catalog\ CAST\ \(public\.box2d\ AS\ public\.box3d\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.box2d\ AS\ public\.geometry\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.box3d\ AS\ box\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.box3d\ AS\ public\.box2d\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.box3d\ AS\ public\.geometry\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.box3d_extent\ AS\ public\.box2d\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.box3d_extent\ AS\ public\.box3d\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.box3d_extent\ AS\ public\.geometry\)\ /,
 /CAST\ pg_catalog\ CAST\ \(bytea\ AS\ public\.geometry\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.chip\ AS\ public\.geometry\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.geometry\ AS\ box\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.geometry\ AS\ public\.box2d\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.geometry\ AS\ public\.box3d\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.geometry\ AS\ bytea\)\ /,
 /CAST\ pg_catalog\ CAST\ \(public\.geometry\ AS\ text\)\ /,
 /CAST\ pg_catalog\ CAST\ \(text\ AS\ public\.geometry\)\ /,
 /TABLE\ public\ geometry_columns\ postgres/,
 /ACL\ public\ geometry_columns\ postgres/,
 /TABLE\ public\ spatial_ref_sys\ postgres/,
 /ACL\ public\ spatial_ref_sys\ postgres/,
 /TABLE\ DATA\ public\ geometry_columns\ postgres/,
 /TABLE\ DATA\ public\ spatial_ref_sys\ postgres/,
 /CONSTRAINT\ public\ geometry_columns_pk\ postgres/,
 /CONSTRAINT\ public\ spatial_ref_sys_pkey\ postgres/,
 /ACL\ \-\ public\ postgres/,
 /SHELL\ TYPE\ public\ gtrgm\ postgres/,
 /FUNCTION\ public\ gtrgm_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ gtrgm_out\(gtrgm\)\ postgres/,
 /TYPE\ public\ gtrgm\ postgres/,
 /FUNCTION\ public\ gin_extract_trgm\(text,\ internal\)\ postgres/,
 /FUNCTION\ public\ gin_extract_trgm\(text,\ internal,\ smallint,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ gin_trgm_consistent\(internal,\ smallint,\ text,\ integer,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ gtrgm_compress\(internal\)\ postgres/,
 /FUNCTION\ public\ gtrgm_consistent\(internal,\ text,\ integer,\ oid,\ internal\)\ postgres/,
 /FUNCTION\ public\ gtrgm_decompress\(internal\)\ postgres/,
 /FUNCTION\ public\ gtrgm_penalty\(internal,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ gtrgm_picksplit\(internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ gtrgm_same\(gtrgm,\ gtrgm,\ internal\)\ postgres/,
 /FUNCTION\ public\ gtrgm_union\(bytea,\ internal\)\ postgres/,
 /FUNCTION\ public\ set_limit\(real\)\ postgres/,
 /FUNCTION\ public\ show_limit\(\)\ postgres/,
 /FUNCTION\ public\ show_trgm\(text\)\ postgres/,
 /FUNCTION\ public\ similarity\(text,\ text\)\ postgres/,
 /FUNCTION\ public\ similarity_op\(text,\ text\)\ postgres/,
 /OPERATOR\ public\ %\ postgres/,
 /OPERATOR\ CLASS\ public\ gin_trgm_ops\ postgres/,
 /OPERATOR\ CLASS\ public\ gist_trgm_ops\ postgres/,
 /ACL\ \-\ public\ postgres/,
 /SHELL\ TYPE\ public\ lquery\ postgres/,
 /FUNCTION\ public\ lquery_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ lquery_out\(lquery\)\ postgres/,
 /TYPE\ public\ lquery\ postgres/,
 /SHELL\ TYPE\ public\ ltree\ postgres/,
 /FUNCTION\ public\ ltree_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ ltree_out\(ltree\)\ postgres/,
 /TYPE\ public\ ltree\ postgres/,
 /SHELL\ TYPE\ public\ ltree_gist\ postgres/,
 /FUNCTION\ public\ ltree_gist_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ ltree_gist_out\(ltree_gist\)\ postgres/,
 /TYPE\ public\ ltree_gist\ postgres/,
 /SHELL\ TYPE\ public\ ltxtquery\ postgres/,
 /FUNCTION\ public\ ltxtq_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ ltxtq_out\(ltxtquery\)\ postgres/,
 /TYPE\ public\ ltxtquery\ postgres/,
 /FUNCTION\ public\ _lt_q_regex\(ltree\[\],\ lquery\[\]\)\ postgres/,
 /FUNCTION\ public\ _lt_q_rregex\(lquery\[\],\ ltree\[\]\)\ postgres/,
 /FUNCTION\ public\ _ltq_extract_regex\(ltree\[\],\ lquery\)\ postgres/,
 /FUNCTION\ public\ _ltq_regex\(ltree\[\],\ lquery\)\ postgres/,
 /FUNCTION\ public\ _ltq_rregex\(lquery,\ ltree\[\]\)\ postgres/,
 /FUNCTION\ public\ _ltree_compress\(internal\)\ postgres/,
 /FUNCTION\ public\ _ltree_consistent\(internal,\ internal,\ smallint,\ oid,\ internal\)\ postgres/,
 /FUNCTION\ public\ _ltree_extract_isparent\(ltree\[\],\ ltree\)\ postgres/,
 /FUNCTION\ public\ _ltree_extract_risparent\(ltree\[\],\ ltree\)\ postgres/,
 /FUNCTION\ public\ _ltree_isparent\(ltree\[\],\ ltree\)\ postgres/,
 /FUNCTION\ public\ _ltree_penalty\(internal,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ _ltree_picksplit\(internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ _ltree_r_isparent\(ltree,\ ltree\[\]\)\ postgres/,
 /FUNCTION\ public\ _ltree_r_risparent\(ltree,\ ltree\[\]\)\ postgres/,
 /FUNCTION\ public\ _ltree_risparent\(ltree\[\],\ ltree\)\ postgres/,
 /FUNCTION\ public\ _ltree_same\(internal,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ _ltree_union\(internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ _ltxtq_exec\(ltree\[\],\ ltxtquery\)\ postgres/,
 /FUNCTION\ public\ _ltxtq_extract_exec\(ltree\[\],\ ltxtquery\)\ postgres/,
 /FUNCTION\ public\ _ltxtq_rexec\(ltxtquery,\ ltree\[\]\)\ postgres/,
 /FUNCTION\ public\ index\(ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ index\(ltree,\ ltree,\ integer\)\ postgres/,
 /FUNCTION\ public\ lca\(ltree\[\]\)\ postgres/,
 /FUNCTION\ public\ lca\(ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ lca\(ltree,\ ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ lca\(ltree,\ ltree,\ ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ lca\(ltree,\ ltree,\ ltree,\ ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ lca\(ltree,\ ltree,\ ltree,\ ltree,\ ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ lca\(ltree,\ ltree,\ ltree,\ ltree,\ ltree,\ ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ lca\(ltree,\ ltree,\ ltree,\ ltree,\ ltree,\ ltree,\ ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ lt_q_regex\(ltree,\ lquery\[\]\)\ postgres/,
 /FUNCTION\ public\ lt_q_rregex\(lquery\[\],\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltq_regex\(ltree,\ lquery\)\ postgres/,
 /FUNCTION\ public\ ltq_rregex\(lquery,\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltree2text\(ltree\)\ postgres/,
 /FUNCTION\ public\ ltree_addltree\(ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltree_addtext\(ltree,\ text\)\ postgres/,
 /FUNCTION\ public\ ltree_cmp\(ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltree_compress\(internal\)\ postgres/,
 /FUNCTION\ public\ ltree_consistent\(internal,\ internal,\ smallint,\ oid,\ internal\)\ postgres/,
 /FUNCTION\ public\ ltree_decompress\(internal\)\ postgres/,
 /FUNCTION\ public\ ltree_eq\(ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltree_ge\(ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltree_gt\(ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltree_isparent\(ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltree_le\(ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltree_lt\(ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltree_ne\(ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltree_penalty\(internal,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ ltree_picksplit\(internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ ltree_risparent\(ltree,\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltree_same\(internal,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ ltree_textadd\(text,\ ltree\)\ postgres/,
 /FUNCTION\ public\ ltree_union\(internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ ltreeparentsel\(internal,\ oid,\ internal,\ integer\)\ postgres/,
 /FUNCTION\ public\ ltxtq_exec\(ltree,\ ltxtquery\)\ postgres/,
 /FUNCTION\ public\ ltxtq_rexec\(ltxtquery,\ ltree\)\ postgres/,
 /FUNCTION\ public\ nlevel\(ltree\)\ postgres/,
 /FUNCTION\ public\ subltree\(ltree,\ integer,\ integer\)\ postgres/,
 /FUNCTION\ public\ subpath\(ltree,\ integer,\ integer\)\ postgres/,
 /FUNCTION\ public\ subpath\(ltree,\ integer\)\ postgres/,
 /FUNCTION\ public\ text2ltree\(text\)\ postgres/,
 /OPERATOR\ public\ <\ postgres/,
 /OPERATOR\ public\ <=\ postgres/,
 /OPERATOR\ public\ <>\ postgres/,
 /OPERATOR\ public\ <@\ postgres/,
 /OPERATOR\ public\ <@\ postgres/,
 /OPERATOR\ public\ <@\ postgres/,
 /OPERATOR\ public\ =\ postgres/,
 /OPERATOR\ public\ >\ postgres/,
 /OPERATOR\ public\ >=\ postgres/,
 /OPERATOR\ public\ \?\ postgres/,
 /OPERATOR\ public\ \?\ postgres/,
 /OPERATOR\ public\ \?\ postgres/,
 /OPERATOR\ public\ \?\ postgres/,
 /OPERATOR\ public\ \?<@\ postgres/,
 /OPERATOR\ public\ \?@\ postgres/,
 /OPERATOR\ public\ \?@>\ postgres/,
 /OPERATOR\ public\ \?~\ postgres/,
 /OPERATOR\ public\ @\ postgres/,
 /OPERATOR\ public\ @\ postgres/,
 /OPERATOR\ public\ @\ postgres/,
 /OPERATOR\ public\ @\ postgres/,
 /OPERATOR\ public\ @>\ postgres/,
 /OPERATOR\ public\ @>\ postgres/,
 /OPERATOR\ public\ @>\ postgres/,
 /OPERATOR\ public\ \^<@\ postgres/,
 /OPERATOR\ public\ \^<@\ postgres/,
 /OPERATOR\ public\ \^<@\ postgres/,
 /OPERATOR\ public\ \^\?\ postgres/,
 /OPERATOR\ public\ \^\?\ postgres/,
 /OPERATOR\ public\ \^\?\ postgres/,
 /OPERATOR\ public\ \^\?\ postgres/,
 /OPERATOR\ public\ \^@\ postgres/,
 /OPERATOR\ public\ \^@\ postgres/,
 /OPERATOR\ public\ \^@\ postgres/,
 /OPERATOR\ public\ \^@\ postgres/,
 /OPERATOR\ public\ \^@>\ postgres/,
 /OPERATOR\ public\ \^@>\ postgres/,
 /OPERATOR\ public\ \^@>\ postgres/,
 /OPERATOR\ public\ \^~\ postgres/,
 /OPERATOR\ public\ \^~\ postgres/,
 /OPERATOR\ public\ \^~\ postgres/,
 /OPERATOR\ public\ \^~\ postgres/,
 /OPERATOR\ public\ \|\|\ postgres/,
 /OPERATOR\ public\ \|\|\ postgres/,
 /OPERATOR\ public\ \|\|\ postgres/,
 /OPERATOR\ public\ ~\ postgres/,
 /OPERATOR\ public\ ~\ postgres/,
 /OPERATOR\ public\ ~\ postgres/,
 /OPERATOR\ public\ ~\ postgres/,
 /OPERATOR\ CLASS\ public\ gist__ltree_ops\ postgres/,
 /OPERATOR\ CLASS\ public\ gist_ltree_ops\ postgres/,
 /OPERATOR\ CLASS\ public\ ltree_ops\ postgres/,
 /ACL\ \-\ public\ postgres/,
 /SHELL\ TYPE\ public\ intbig_gkey\ postgres/,
 /FUNCTION\ public\ _intbig_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ _intbig_out\(intbig_gkey\)\ postgres/,
 /TYPE\ public\ intbig_gkey\ postgres/,
 /SHELL\ TYPE\ public\ query_int\ postgres/,
 /FUNCTION\ public\ bqarr_in\(cstring\)\ postgres/,
 /FUNCTION\ public\ bqarr_out\(query_int\)\ postgres/,
 /TYPE\ public\ query_int\ postgres/,
 /FUNCTION\ public\ _int_contained\(integer\[\],\ integer\[\]\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ _int_contained\(integer\[\],\ integer\[\]\)\ postgres/,
 /FUNCTION\ public\ _int_contains\(integer\[\],\ integer\[\]\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ _int_contains\(integer\[\],\ integer\[\]\)\ postgres/,
 /FUNCTION\ public\ _int_different\(integer\[\],\ integer\[\]\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ _int_different\(integer\[\],\ integer\[\]\)\ postgres/,
 /FUNCTION\ public\ _int_inter\(integer\[\],\ integer\[\]\)\ postgres/,
 /FUNCTION\ public\ _int_overlap\(integer\[\],\ integer\[\]\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ _int_overlap\(integer\[\],\ integer\[\]\)\ postgres/,
 /FUNCTION\ public\ _int_same\(integer\[\],\ integer\[\]\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ _int_same\(integer\[\],\ integer\[\]\)\ postgres/,
 /FUNCTION\ public\ _int_union\(integer\[\],\ integer\[\]\)\ postgres/,
 /FUNCTION\ public\ boolop\(integer\[\],\ query_int\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ boolop\(integer\[\],\ query_int\)\ postgres/,
 /FUNCTION\ public\ g_int_compress\(internal\)\ postgres/,
 /FUNCTION\ public\ g_int_consistent\(internal,\ integer\[\],\ integer,\ oid,\ internal\)\ postgres/,
 /FUNCTION\ public\ g_int_decompress\(internal\)\ postgres/,
 /FUNCTION\ public\ g_int_penalty\(internal,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ g_int_picksplit\(internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ g_int_same\(integer\[\],\ integer\[\],\ internal\)\ postgres/,
 /FUNCTION\ public\ g_int_union\(internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ g_intbig_compress\(internal\)\ postgres/,
 /FUNCTION\ public\ g_intbig_consistent\(internal,\ internal,\ integer,\ oid,\ internal\)\ postgres/,
 /FUNCTION\ public\ g_intbig_decompress\(internal\)\ postgres/,
 /FUNCTION\ public\ g_intbig_penalty\(internal,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ g_intbig_picksplit\(internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ g_intbig_same\(internal,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ g_intbig_union\(internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ ginint4_consistent\(internal,\ smallint,\ internal,\ integer,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ ginint4_queryextract\(internal,\ internal,\ smallint,\ internal,\ internal\)\ postgres/,
 /FUNCTION\ public\ icount\(integer\[\]\)\ postgres/,
 /FUNCTION\ public\ idx\(integer\[\],\ integer\)\ postgres/,
 /FUNCTION\ public\ intarray_del_elem\(integer\[\],\ integer\)\ postgres/,
 /FUNCTION\ public\ intarray_push_array\(integer\[\],\ integer\[\]\)\ postgres/,
 /FUNCTION\ public\ intarray_push_elem\(integer\[\],\ integer\)\ postgres/,
 /FUNCTION\ public\ intset\(integer\)\ postgres/,
 /FUNCTION\ public\ intset_subtract\(integer\[\],\ integer\[\]\)\ postgres/,
 /FUNCTION\ public\ intset_union_elem\(integer\[\],\ integer\)\ postgres/,
 /FUNCTION\ public\ querytree\(query_int\)\ postgres/,
 /FUNCTION\ public\ rboolop\(query_int,\ integer\[\]\)\ postgres/,
 /COMMENT\ public\ FUNCTION\ rboolop\(query_int,\ integer\[\]\)\ postgres/,
 /FUNCTION\ public\ sort\(integer\[\],\ text\)\ postgres/,
 /FUNCTION\ public\ sort\(integer\[\]\)\ postgres/,
 /FUNCTION\ public\ sort_asc\(integer\[\]\)\ postgres/,
 /FUNCTION\ public\ sort_desc\(integer\[\]\)\ postgres/,
 /FUNCTION\ public\ subarray\(integer\[\],\ integer,\ integer\)\ postgres/,
 /FUNCTION\ public\ subarray\(integer\[\],\ integer\)\ postgres/,
 /FUNCTION\ public\ uniq\(integer\[\]\)\ postgres/,
 /OPERATOR\ public\ \#\ postgres/,
 /OPERATOR\ public\ \#\ postgres/,
 /OPERATOR\ public\ &\ postgres/,
 /OPERATOR\ public\ &&\ postgres/,
 /OPERATOR\ public\ \+\ postgres/,
 /OPERATOR\ public\ \+\ postgres/,
 /OPERATOR\ public\ \-\ postgres/,
 /OPERATOR\ public\ \-\ postgres/,
 /OPERATOR\ public\ <@\ postgres/,
 /OPERATOR\ public\ @\ postgres/,
 /OPERATOR\ public\ @>\ postgres/,
 /OPERATOR\ public\ @@\ postgres/,
 /OPERATOR\ public\ \|\ postgres/,
 /OPERATOR\ public\ \|\ postgres/,
 /OPERATOR\ public\ ~\ postgres/,
 /OPERATOR\ public\ ~~\ postgres/,
 /OPERATOR\ CLASS\ public\ gin__int_ops\ postgres/,
 /OPERATOR\ CLASS\ public\ gist__int_ops\ postgres/,
 /OPERATOR\ CLASS\ public\ gist__intbig_ops\ postgres/]


$stdin.each_line do |line|
  if REGEXPS.inject(nil) do |found,pattern|
    unless found then
      if line =~ pattern then
        found = true
      end
    end
    found
  end then
    # Ignore elements provided by already postgis enabled template database
  else
    puts line # This line is NOT part of template_gis
  end
end 
